swagger: "2.0"
info:
  title: wefly-api
  description: WeFly API
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /api/tracklist:
    get:
      summary: list tracks of a day
      operationId: tracklist
      x-google-backend:
        address: https://wefly-api-server-qmzkppaiia-uc.a.run.app/api/tracklist
      parameters:
        - in: query
          name: date
          type: string
          required: true
          description: date
      responses:
        "200":
          description: A successful response
          schema:
            type: string
        "400":
          description: Bad Request
        "404":
          description: Not found
        "500":
          description: Internal Server Error
  /api/tracks:
    get:
      summary: get timeseries data of tracks
      operationId: tracks
      x-google-backend:
        address: https://wefly-api-server-qmzkppaiia-uc.a.run.app/api/tracks
      parameters:
        - in: query
          name: date
          type: string
          required: true
          description: date
      responses:
        "200":
          description: A successful response
          schema:
            type: string
        "400":
          description: Bad Request
        "404":
          description: Not found
        "500":
          description: Internal Server Error
  /**:
    get:
      summary: WeFly main page
      operationId: wefly
      x-google-backend:
        address: https://wefly-client-qmzkppaiia-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        "200":
          description: A successful response
          schema:
            type: string
