name: 'Google Cloud Login'
description: 'Authenticate to Google Cloud'
inputs:
  service_account_email:
    description: 'The service account email to authenticate with'
    required: true
  workload_identity_provider:
    description: 'The workload identity provider to authenticate with'
    required: true
runs:
  using: 'composite'
  steps:
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        service_account: ${{ inputs.service_account_email }}
        workload_identity_provider: ${{ inputs.workload_identity_provider }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
