name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: checkout repository
    - uses: actions/setup-node@v4.0.1
    - name: Build the Docker image
      run: npm run deploy
