name: Pre-Merge check

permissions:
  contents: read

on:
  push:
    branches-ignore:
      - staging
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: checkout repository

    - name: npm install
      run: npm install
      working-directory: "./common"

    - name: npm install
      run: npm install
      working-directory: "./client"

    - name: npm install
      run: npm install
      working-directory: "./api-server"

    - name: npm install
      run: npm install
      working-directory: "./track_loader"

    - name: run tests
      run: npm run test-all
      working-directory: "./"
